import type { Models } from 'appwrite';

// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types -l ts ./src/api/types/`.

export enum DaysRecordsMood {
    HAPPY = "happy",
    SAD = "sad",
    NEUTRAL = "neutral",
    ENERGETIC = "energetic",
    TIRED = "tired"
}

export type Posts = Models.Row & {
    title: string | null;
    likes: number | null;
}

export type DaysRecords = Models.Row & {
    sleep_start: string;
    sleep_end: string;
    notes: string | null;
    mood: DaysRecordsMood | null;
    sleep_score: number | null;
    date: string;
}
