// import type { Models } from "appwrite";

// // This file is auto-generated by the Appwrite CLI.
// // You can regenerate it by running `appwrite types -l ts ./src/api/types/`.

// export enum DaysRecordsMood {
// 	HAPPY = "happy",
// 	SAD = "sad",
// 	NEUTRAL = "neutral",
// 	ENERGETIC = "energetic",
// 	TIRED = "tired",
// }

// export type ActivitiesType = "task" | "habit";

// export type Posts = Models.Row & {
// 	title: string | null;
// 	banner_url: string | null;
// 	author_id: string | null;
// 	content: string | null;
// };

// export type DaysRecords = Models.Row & {
// 	sleep_start: string | null;
// 	sleep_end: string | null;
// 	notes: string | null;
// 	mood: DaysRecordsMood | null;
// 	sleep_score: number | null;
// 	date: string;
// };

// export type HabitsOld = Models.Row & {
// 	title: string | null;
// 	icon: string | null;
// };

// export type HabitsRecordsOld = Models.Row & {
// 	completed: boolean;
// 	date: string;
// 	habit_id: string;
// };

// export type Users = Models.Row & {
// 	avatar: string | null;
// 	user_id: string;
// 	nickname: string | null;
// 	description: string | null;
// };

// export type Goals = Models.Row & {
// 	title: string | null;
// 	description: string | null;
// 	parent_id: string | null;
// 	completed: boolean;
// };

// export type Routines = Models.Row & {};

// export type Habits = Models.Row & {
// 	title: string | null;
// 	icon: string | null;
// };

// export type HabitsRecords = Models.Row & {
// 	date: string | null;
// 	completed: boolean;
// 	habit_id: string;
// };

// export type Activities = Models.Row & {
// 	title: string | null;
// 	description: string | null;
// 	type: ActivitiesType;
// 	icon: string | null;
// 	user_id: string;
// };

// export type ActivityEntries = Models.Row & {
// 	date: string;
// 	activity_id: string;
// 	completed: boolean;
// 	user_id: string | null;
// };
