/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../src/pages/__root'
import { Route as IndexRouteImport } from './../src/pages/index'
import { Route as UsersIndexRouteImport } from './../src/pages/users/index'
import { Route as TestIndexRouteImport } from './../src/pages/test/index'
import { Route as ProjectsIndexRouteImport } from './../src/pages/projects/index'
import { Route as IssuesIndexRouteImport } from './../src/pages/issues/index'
import { Route as UsersUser_idRouteImport } from './../src/pages/users/$user_id'
import { Route as IssuesIssue_idRouteImport } from './../src/pages/issues/$issue_id'
import { Route as ProjectsCustom_idRouteRouteImport } from './../src/pages/projects/$custom_id/route'
import { Route as ProjectsCustom_idIndexRouteImport } from './../src/pages/projects/$custom_id/index'
import { Route as ProjectsCustom_idIssuesRouteImport } from './../src/pages/projects/$custom_id/issues'
import { Route as ProjectsCustom_idModulesIndexRouteImport } from './../src/pages/projects/$custom_id/modules/index'
import { Route as ProjectsCustom_idModulesModule_idRouteImport } from './../src/pages/projects/$custom_id/modules/$module_id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestIndexRoute = TestIndexRouteImport.update({
  id: '/test/',
  path: '/test/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesIndexRoute = IssuesIndexRouteImport.update({
  id: '/issues/',
  path: '/issues/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUser_idRoute = UsersUser_idRouteImport.update({
  id: '/users/$user_id',
  path: '/users/$user_id',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesIssue_idRoute = IssuesIssue_idRouteImport.update({
  id: '/issues/$issue_id',
  path: '/issues/$issue_id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsCustom_idRouteRoute = ProjectsCustom_idRouteRouteImport.update({
  id: '/projects/$custom_id',
  path: '/projects/$custom_id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsCustom_idIndexRoute = ProjectsCustom_idIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsCustom_idRouteRoute,
} as any)
const ProjectsCustom_idIssuesRoute = ProjectsCustom_idIssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => ProjectsCustom_idRouteRoute,
} as any)
const ProjectsCustom_idModulesIndexRoute =
  ProjectsCustom_idModulesIndexRouteImport.update({
    id: '/modules/',
    path: '/modules/',
    getParentRoute: () => ProjectsCustom_idRouteRoute,
  } as any)
const ProjectsCustom_idModulesModule_idRoute =
  ProjectsCustom_idModulesModule_idRouteImport.update({
    id: '/modules/$module_id',
    path: '/modules/$module_id',
    getParentRoute: () => ProjectsCustom_idRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects/$custom_id': typeof ProjectsCustom_idRouteRouteWithChildren
  '/issues/$issue_id': typeof IssuesIssue_idRoute
  '/users/$user_id': typeof UsersUser_idRoute
  '/issues': typeof IssuesIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/test': typeof TestIndexRoute
  '/users': typeof UsersIndexRoute
  '/projects/$custom_id/issues': typeof ProjectsCustom_idIssuesRoute
  '/projects/$custom_id/': typeof ProjectsCustom_idIndexRoute
  '/projects/$custom_id/modules/$module_id': typeof ProjectsCustom_idModulesModule_idRoute
  '/projects/$custom_id/modules': typeof ProjectsCustom_idModulesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/issues/$issue_id': typeof IssuesIssue_idRoute
  '/users/$user_id': typeof UsersUser_idRoute
  '/issues': typeof IssuesIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/test': typeof TestIndexRoute
  '/users': typeof UsersIndexRoute
  '/projects/$custom_id/issues': typeof ProjectsCustom_idIssuesRoute
  '/projects/$custom_id': typeof ProjectsCustom_idIndexRoute
  '/projects/$custom_id/modules/$module_id': typeof ProjectsCustom_idModulesModule_idRoute
  '/projects/$custom_id/modules': typeof ProjectsCustom_idModulesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects/$custom_id': typeof ProjectsCustom_idRouteRouteWithChildren
  '/issues/$issue_id': typeof IssuesIssue_idRoute
  '/users/$user_id': typeof UsersUser_idRoute
  '/issues/': typeof IssuesIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/test/': typeof TestIndexRoute
  '/users/': typeof UsersIndexRoute
  '/projects/$custom_id/issues': typeof ProjectsCustom_idIssuesRoute
  '/projects/$custom_id/': typeof ProjectsCustom_idIndexRoute
  '/projects/$custom_id/modules/$module_id': typeof ProjectsCustom_idModulesModule_idRoute
  '/projects/$custom_id/modules/': typeof ProjectsCustom_idModulesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/projects/$custom_id'
    | '/issues/$issue_id'
    | '/users/$user_id'
    | '/issues'
    | '/projects'
    | '/test'
    | '/users'
    | '/projects/$custom_id/issues'
    | '/projects/$custom_id/'
    | '/projects/$custom_id/modules/$module_id'
    | '/projects/$custom_id/modules'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/issues/$issue_id'
    | '/users/$user_id'
    | '/issues'
    | '/projects'
    | '/test'
    | '/users'
    | '/projects/$custom_id/issues'
    | '/projects/$custom_id'
    | '/projects/$custom_id/modules/$module_id'
    | '/projects/$custom_id/modules'
  id:
    | '__root__'
    | '/'
    | '/projects/$custom_id'
    | '/issues/$issue_id'
    | '/users/$user_id'
    | '/issues/'
    | '/projects/'
    | '/test/'
    | '/users/'
    | '/projects/$custom_id/issues'
    | '/projects/$custom_id/'
    | '/projects/$custom_id/modules/$module_id'
    | '/projects/$custom_id/modules/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsCustom_idRouteRoute: typeof ProjectsCustom_idRouteRouteWithChildren
  IssuesIssue_idRoute: typeof IssuesIssue_idRoute
  UsersUser_idRoute: typeof UsersUser_idRoute
  IssuesIndexRoute: typeof IssuesIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  TestIndexRoute: typeof TestIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/': {
      id: '/test/'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues/': {
      id: '/issues/'
      path: '/issues'
      fullPath: '/issues'
      preLoaderRoute: typeof IssuesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$user_id': {
      id: '/users/$user_id'
      path: '/users/$user_id'
      fullPath: '/users/$user_id'
      preLoaderRoute: typeof UsersUser_idRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues/$issue_id': {
      id: '/issues/$issue_id'
      path: '/issues/$issue_id'
      fullPath: '/issues/$issue_id'
      preLoaderRoute: typeof IssuesIssue_idRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$custom_id': {
      id: '/projects/$custom_id'
      path: '/projects/$custom_id'
      fullPath: '/projects/$custom_id'
      preLoaderRoute: typeof ProjectsCustom_idRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$custom_id/': {
      id: '/projects/$custom_id/'
      path: '/'
      fullPath: '/projects/$custom_id/'
      preLoaderRoute: typeof ProjectsCustom_idIndexRouteImport
      parentRoute: typeof ProjectsCustom_idRouteRoute
    }
    '/projects/$custom_id/issues': {
      id: '/projects/$custom_id/issues'
      path: '/issues'
      fullPath: '/projects/$custom_id/issues'
      preLoaderRoute: typeof ProjectsCustom_idIssuesRouteImport
      parentRoute: typeof ProjectsCustom_idRouteRoute
    }
    '/projects/$custom_id/modules/': {
      id: '/projects/$custom_id/modules/'
      path: '/modules'
      fullPath: '/projects/$custom_id/modules'
      preLoaderRoute: typeof ProjectsCustom_idModulesIndexRouteImport
      parentRoute: typeof ProjectsCustom_idRouteRoute
    }
    '/projects/$custom_id/modules/$module_id': {
      id: '/projects/$custom_id/modules/$module_id'
      path: '/modules/$module_id'
      fullPath: '/projects/$custom_id/modules/$module_id'
      preLoaderRoute: typeof ProjectsCustom_idModulesModule_idRouteImport
      parentRoute: typeof ProjectsCustom_idRouteRoute
    }
  }
}

interface ProjectsCustom_idRouteRouteChildren {
  ProjectsCustom_idIssuesRoute: typeof ProjectsCustom_idIssuesRoute
  ProjectsCustom_idIndexRoute: typeof ProjectsCustom_idIndexRoute
  ProjectsCustom_idModulesModule_idRoute: typeof ProjectsCustom_idModulesModule_idRoute
  ProjectsCustom_idModulesIndexRoute: typeof ProjectsCustom_idModulesIndexRoute
}

const ProjectsCustom_idRouteRouteChildren: ProjectsCustom_idRouteRouteChildren =
  {
    ProjectsCustom_idIssuesRoute: ProjectsCustom_idIssuesRoute,
    ProjectsCustom_idIndexRoute: ProjectsCustom_idIndexRoute,
    ProjectsCustom_idModulesModule_idRoute:
      ProjectsCustom_idModulesModule_idRoute,
    ProjectsCustom_idModulesIndexRoute: ProjectsCustom_idModulesIndexRoute,
  }

const ProjectsCustom_idRouteRouteWithChildren =
  ProjectsCustom_idRouteRoute._addFileChildren(
    ProjectsCustom_idRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsCustom_idRouteRoute: ProjectsCustom_idRouteRouteWithChildren,
  IssuesIssue_idRoute: IssuesIssue_idRoute,
  UsersUser_idRoute: UsersUser_idRoute,
  IssuesIndexRoute: IssuesIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  TestIndexRoute: TestIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
